---
- hosts: all
  become: yes
  strategy: linear
  tasks:
    - name: Package installation
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - htop
        - nmap
        - apache2
        - net-tools
        - vim
        - ncdu
        - iftop
        - curl

    - name: start apache2
        service:
            name: apache2
            state: started