---
- hosts: all
  become: yes
  strategy: linear
  tasks:
    - name: Package installation
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - htop
        - nmap
        - httpd
        - net-tools
        - vim
        - ncdu
        - iftop
        - curl

    #- name: start apache2
        #service:
            #name: apache2
            #state: started

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "httpd"
        mode: '0755'

    - name: Copy index test page
      copy:
        src: "/home/dominik.veleta/Desktop/Ansible-test/index.html"
        dest: "/var/www/{{ http_host }}/index.html"

     #- name: Reload Apache
      #service:
        #name: apache2
        #state: reloaded
...