---
- hosts: all
  become: yes
  strategy: linear
  vars:
    http_host: test
  tasks:
    - name: Package installation
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - htop
        - nmap
        - nginx
        - net-tools
        - vim
        - ncdu
        - iftop
        - curl

    - name: start nginx
      service:
        name: nginx
        state: started

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "nginx"
        mode: '0755'

    - name: Copy index test page
      copy:
        src: "/home/dominik.veleta/Desktop/Ansible-test/index.html"
        dest: "/var/www/{{ http_host }}/index.html"

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
...